# Generated by Django 5.2.6 on 2025-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_competitor_delay_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='clear_after_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
