# Generated by Django 5.2.6 on 2025-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drop_clear_after_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('missed', 'Missed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='drop',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
